import React from 'react';
import KnowledgeGraph from './KnowledgeGraph.jsx';
import {archiveAssets} from './archive-assets.js';
import {photos} from './sphere-layout.js';
import {cultureThemes,themeCounts,knowledgeSources} from './culture-knowledge.js';
import {themeEnglish} from './localization.js';

export default function CultureBoard({lang,category,setCategory,setSelected,children,playing,setPlaying,depth,setDepth,setReset}){
 const tr=(zh,en)=>lang==='zh'?zh:en;
 return <>
 <main className="knowledge-board">
 <section className="board-heading intro"><span className="eyebrow">{tr('齐文化 / 空间知识图谱','QI CULTURE / SPATIAL KNOWLEDGE ATLAS')}</span><h1>{tr('齐文化转译 / 信息整合','Cultural translation / information integration')}</h1><p>{tr('将初步提出的四象限框架应用于文物、工业档案和齐文化故事。','Apply the provisional four-quadrant framework to objects, industrial archives and cultural stories.')}<br/>{tr('从多元线索到共同场域，汇聚为一颗持续生长的文化球。','Diverse fragments converge into a shared, evolving cultural sphere.')}</p></section>
 <div className="board-corner">{tr('研究—关联—可视化','RESEARCH — CONNECT — VISUALIZE')}<br/>{tr('齐文化记忆的空间重构','A spatial reconstruction of Qi cultural memory')}</div>
 <KnowledgeGraph lang={lang} active={category} onTheme={setCategory} onSelect={asset=>setSelected(photos.find(p=>asset.story?p.id!==undefined&&p.title===asset.title:p.src===asset.src))}/>
 <section className="visual"><div className="visual-top"><span>{tr('03 / 文化球','03 / THE CULTURAL SPHERE')}</span></div>{children}<div className="drag-hint">{tr('拖动旋转 · 点击影像探索','Drag to rotate · Select an image to explore')}</div></section>
 <section className="board-notes" aria-live="polite"><span className="eyebrow">{tr('万千碎片，汇聚共同场域','FROM FRAGMENTS TO A SHARED WHOLE')}</span><h2>{category===null?tr('多元文化的空间汇聚','A convergence of cultural memories'):tr(cultureThemes[category].cn+' / 主题关联',themeEnglish[category].short)}</h2><p>{category===null?tr('四种文化属性交叉连接文物与近现代工业资料。点击左侧属性，观察关联影像在球面上的分布。','Four cultural themes connect objects and modern industrial archives. Select a theme to reveal its images across the sphere.'):tr(cultureThemes[category].note,themeEnglish[category].note)}</p><div className="archive-metrics"><div><strong>04</strong><span>{tr('文化属性','CULTURAL THEMES')}</span></div><div><strong>{category===null?archiveAssets.length:themeCounts[category]}</strong><span>{category===null?tr('真实资料','ARCHIVES'):tr('关联资料','RELATED ARCHIVES')}</span></div><div><strong>{photos.length}</strong><span>{tr('球面影像','SPHERICAL FRAGMENTS')}</span></div></div><div className="theme-bars">{cultureThemes.map((t,i)=><button key={t.cn} aria-label={tr('筛选'+t.cn,'Filter '+themeEnglish[i].short)} aria-pressed={category===i} onClick={()=>setCategory(category===i?null:i)}><span>{tr(t.cn,themeEnglish[i].short)}</span><i style={{width:themeCounts[i]/archiveAssets.length*100+'%'}}/><small>{themeCounts[i]}</small></button>)}</div></section>
 <div className="board-method">{tr('资料 → 属性 → 空间','ARCHIVES → ATTRIBUTES → SPACE')}<br/><span>{tr('连线为策展主题关联，不代表直接历史因果。','Connections express curatorial associations, not direct historical causation.')}</span></div>
 </main>
 <div className="bottom"><div className="source-note"><span>{tr('资料：用户工业档案 / 齐文化博物院','Sources: user industrial archives / Qi Heritage Museum')}</span><div>{knowledgeSources.map((s,i)=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{tr(s.label,i===0?'Qi cultural spirit · Zibo municipal source':'Innovation & commerce · Zibo cultural plan')} ↗</a>)}</div></div><div className="controls"><button className="play" onClick={()=>setPlaying(!playing)} aria-label={playing?tr('暂停自动旋转','Pause rotation'):tr('开始自动旋转','Start rotation')}><span>{playing?'Ⅱ':'▷'}</span>{playing?tr('暂停旋转','Pause'):tr('自动旋转','Auto rotate')}</button><div className="depth"><label htmlFor="depth">{tr('空间层次','Spatial relief')} <span>{depth.toFixed(1)}×</span></label><input id="depth" type="range" min="0" max="2" step="0.1" value={depth} onChange={e=>setDepth(Number(e.target.value))}/></div><button className="reset" aria-label={tr('重置视角','Reset view')} title={tr('重置视角','Reset view')} onClick={()=>{setReset(x=>x+1);setDepth(0.2);setCategory(null)}}>↺</button></div></div><footer><span>{tr('齐文化 / 知识星图','QI CULTURE / KNOWLEDGE CONSTELLATION')}</span><span>{tr('文化基因 · 器物记忆 · 工业叙事','CULTURAL GENES · OBJECT MEMORIES · INDUSTRIAL STORIES')}</span><span>{tr('01 / 文化转译','01 / CULTURAL TRANSLATION')}</span></footer>
 </>
}
