import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/20135/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
await mkdir('qa',{recursive:true});
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:1600,height:900},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4173',{waitUntil:'networkidle'});
await page.screenshot({path:'qa/desktop.png',animations:'disabled'});
console.log('desktop icons:',await page.locator('.desktop-icon').count());
await page.getByRole('button',{name:'Open MIMESIS—The Shape of AI',exact:true}).click();
await page.locator('.window').waitFor();
await page.locator('.gallery-image').evaluate(im=>im.decode());
await page.screenshot({path:'qa/project.png',animations:'disabled'});
await page.getByRole('button',{name:'Next image',exact:true}).click();
console.log('gallery:',await page.locator('.counter').textContent());
await page.getByRole('button',{name:'View image full screen'}).click();
console.log('lightbox:',await page.locator('#lightbox').evaluate(e=>e.open));
await page.keyboard.press('ArrowRight');await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Minimize MIMESIS — The Shape of AI',exact:true}).click();
await page.getByRole('button',{name:'Restore MIMESIS — The Shape of AI',exact:true}).click();
console.log('restored:',await page.locator('.window:visible').count());
await page.getByRole('button',{name:'Maximize MIMESIS — The Shape of AI',exact:true}).click();
console.log('maximized:',await page.locator('.window.maximized').count());
await page.getByRole('button',{name:'Close MIMESIS — The Shape of AI',exact:true}).click();
await page.getByRole('button',{name:'Open Terminal',exact:true}).click();
await page.getByRole('textbox',{name:'Terminal command'}).fill('ls');await page.keyboard.press('Enter');
console.log('terminal lists projects:',await page.locator('.terminal-output').textContent());
await page.getByRole('button',{name:'Close Terminal — portfolio',exact:true}).click();
await page.getByRole('button',{name:'Search projects',exact:true}).click();
await page.getByRole('searchbox').fill('GAIA');console.log('search results:',await page.locator('.project-card').count());
await page.getByRole('button',{name:'Close Spotlight — Projects',exact:true}).click();
await page.setViewportSize({width:390,height:844});await page.reload({waitUntil:'networkidle'});
await page.screenshot({path:'qa/mobile.png',fullPage:true,animations:'disabled'});
console.log('mobile overflow:',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
await page.getByRole('button',{name:'Open Homeward Memories UI Design',exact:true}).click();
await page.locator('.gallery-image').evaluate(im=>im.decode());
await page.screenshot({path:'qa/mobile-project.png',animations:'disabled'});
console.log('mobile visible window:',await page.locator('.window').boundingBox());
await writeFile('qa/browser-results.json',JSON.stringify({errors},null,2));
console.log('page errors:',errors);await browser.close();
